
package com.thesecretserver.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SSWebServiceSoap", targetNamespace = "urn:thesecretserver.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SSWebServiceSoap {


    /**
     * 
     * @param organization
     * @param username
     * @param domain
     * @param password
     * @return
     *     returns com.thesecretserver.service.AuthenticateResult
     */
    @WebMethod(operationName = "Authenticate", action = "urn:thesecretserver.com/Authenticate")
    @WebResult(name = "AuthenticateResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AuthenticateResponse")
    public AuthenticateResult authenticate(
        @WebParam(name = "username", targetNamespace = "urn:thesecretserver.com")
        String username,
        @WebParam(name = "password", targetNamespace = "urn:thesecretserver.com")
        String password,
        @WebParam(name = "organization", targetNamespace = "urn:thesecretserver.com")
        String organization,
        @WebParam(name = "domain", targetNamespace = "urn:thesecretserver.com")
        String domain);

    /**
     * 
     * @param radiusPassword
     * @param organization
     * @param username
     * @param domain
     * @param password
     * @return
     *     returns com.thesecretserver.service.AuthenticateResult
     */
    @WebMethod(operationName = "AuthenticateRADIUS", action = "urn:thesecretserver.com/AuthenticateRADIUS")
    @WebResult(name = "AuthenticateRADIUSResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "AuthenticateRADIUS", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AuthenticateRADIUS")
    @ResponseWrapper(localName = "AuthenticateRADIUSResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AuthenticateRADIUSResponse")
    public AuthenticateResult authenticateRADIUS(
        @WebParam(name = "username", targetNamespace = "urn:thesecretserver.com")
        String username,
        @WebParam(name = "password", targetNamespace = "urn:thesecretserver.com")
        String password,
        @WebParam(name = "organization", targetNamespace = "urn:thesecretserver.com")
        String organization,
        @WebParam(name = "domain", targetNamespace = "urn:thesecretserver.com")
        String domain,
        @WebParam(name = "radiusPassword", targetNamespace = "urn:thesecretserver.com")
        String radiusPassword);

    /**
     * 
     * @param token
     * @return
     *     returns com.thesecretserver.service.TokenIsValidResult
     */
    @WebMethod(operationName = "GetTokenIsValid", action = "urn:thesecretserver.com/GetTokenIsValid")
    @WebResult(name = "GetTokenIsValidResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetTokenIsValid", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetTokenIsValid")
    @ResponseWrapper(localName = "GetTokenIsValidResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetTokenIsValidResponse")
    public TokenIsValidResult getTokenIsValid(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token);

    /**
     * 
     * @param secretId
     * @param token
     * @return
     *     returns com.thesecretserver.service.GetSecretResult
     */
    @WebMethod(operationName = "GetSecret", action = "urn:thesecretserver.com/GetSecret")
    @WebResult(name = "GetSecretResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetSecret", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecret")
    @ResponseWrapper(localName = "GetSecretResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretResponse")
    public GetSecretResult getSecret(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId);

    /**
     * 
     * @param secretId
     * @param token
     * @return
     *     returns com.thesecretserver.service.GetCheckOutStatusResult
     */
    @WebMethod(operationName = "GetCheckOutStatus", action = "urn:thesecretserver.com/GetCheckOutStatus")
    @WebResult(name = "GetCheckOutStatusResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetCheckOutStatus", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetCheckOutStatus")
    @ResponseWrapper(localName = "GetCheckOutStatusResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetCheckOutStatusResponse")
    public GetCheckOutStatusResult getCheckOutStatus(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId);

    /**
     * 
     * @param token
     * @param newPassword
     * @param currentPassword
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "ChangePassword", action = "urn:thesecretserver.com/ChangePassword")
    @WebResult(name = "ChangePasswordResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.ChangePasswordResponse")
    public WebServiceResult changePassword(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "currentPassword", targetNamespace = "urn:thesecretserver.com")
        String currentPassword,
        @WebParam(name = "newPassword", targetNamespace = "urn:thesecretserver.com")
        String newPassword);

    /**
     * 
     * @param token
     * @param url
     * @return
     *     returns com.thesecretserver.service.GetWebPasswordResult
     */
    @WebMethod(operationName = "SearchWebPasswordsForUrl", action = "urn:thesecretserver.com/SearchWebPasswordsForUrl")
    @WebResult(name = "SearchWebPasswordsForUrlResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "SearchWebPasswordsForUrl", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchWebPasswordsForUrl")
    @ResponseWrapper(localName = "SearchWebPasswordsForUrlResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchWebPasswordsForUrlResponse")
    public GetWebPasswordResult searchWebPasswordsForUrl(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "url", targetNamespace = "urn:thesecretserver.com")
        String url);

    /**
     * 
     * @param searchTerm
     * @param token
     * @param showDeleted
     * @param fieldName
     * @return
     *     returns com.thesecretserver.service.GetSecretsByFieldValueResult
     */
    @WebMethod(operationName = "GetSecretsByFieldValue", action = "urn:thesecretserver.com/GetSecretsByFieldValue")
    @WebResult(name = "GetSecretsByFieldValueResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetSecretsByFieldValue", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretsByFieldValue")
    @ResponseWrapper(localName = "GetSecretsByFieldValueResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretsByFieldValueResponse")
    public GetSecretsByFieldValueResult getSecretsByFieldValue(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "fieldName", targetNamespace = "urn:thesecretserver.com")
        String fieldName,
        @WebParam(name = "searchTerm", targetNamespace = "urn:thesecretserver.com")
        String searchTerm,
        @WebParam(name = "showDeleted", targetNamespace = "urn:thesecretserver.com")
        boolean showDeleted);

    /**
     * 
     * @param token
     * @param newUser
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "AddUser", action = "urn:thesecretserver.com/AddUser")
    @WebResult(name = "AddUserResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "AddUser", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AddUser")
    @ResponseWrapper(localName = "AddUserResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AddUserResponse")
    public WebServiceResult addUser(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "newUser", targetNamespace = "urn:thesecretserver.com")
        User newUser);

    /**
     * 
     * @param searchTerm
     * @param token
     * @return
     *     returns com.thesecretserver.service.SearchSecretsResult
     */
    @WebMethod(operationName = "SearchSecrets", action = "urn:thesecretserver.com/SearchSecrets")
    @WebResult(name = "SearchSecretsResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "SearchSecrets", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchSecrets")
    @ResponseWrapper(localName = "SearchSecretsResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchSecretsResponse")
    public SearchSecretsResult searchSecrets(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "searchTerm", targetNamespace = "urn:thesecretserver.com")
        String searchTerm);

    /**
     * 
     * @param searchTerm
     * @param token
     * @param includeSubFolders
     * @param folderId
     * @return
     *     returns com.thesecretserver.service.SearchSecretsResult
     */
    @WebMethod(operationName = "SearchSecretsByFolder", action = "urn:thesecretserver.com/SearchSecretsByFolder")
    @WebResult(name = "SearchSecretsByFolderResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "SearchSecretsByFolder", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchSecretsByFolder")
    @ResponseWrapper(localName = "SearchSecretsByFolderResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchSecretsByFolderResponse")
    public SearchSecretsResult searchSecretsByFolder(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "searchTerm", targetNamespace = "urn:thesecretserver.com")
        String searchTerm,
        @WebParam(name = "folderId", targetNamespace = "urn:thesecretserver.com")
        Integer folderId,
        @WebParam(name = "includeSubFolders", targetNamespace = "urn:thesecretserver.com")
        boolean includeSubFolders);

    /**
     * 
     * @param token
     * @return
     *     returns com.thesecretserver.service.GetFavoritesResult
     */
    @WebMethod(operationName = "GetFavorites", action = "urn:thesecretserver.com/GetFavorites")
    @WebResult(name = "GetFavoritesResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetFavorites", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetFavorites")
    @ResponseWrapper(localName = "GetFavoritesResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetFavoritesResponse")
    public GetFavoritesResult getFavorites(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token);

    /**
     * 
     * @param secretId
     * @param token
     * @param isFavorite
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "UpdateIsFavorite", action = "urn:thesecretserver.com/UpdateIsFavorite")
    @WebResult(name = "UpdateIsFavoriteResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "UpdateIsFavorite", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UpdateIsFavorite")
    @ResponseWrapper(localName = "UpdateIsFavoriteResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UpdateIsFavoriteResponse")
    public WebServiceResult updateIsFavorite(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId,
        @WebParam(name = "isFavorite", targetNamespace = "urn:thesecretserver.com")
        boolean isFavorite);

    /**
     * 
     * @param token
     * @param secretItemValues
     * @param secretFieldIds
     * @param secretTypeId
     * @param folderId
     * @param secretName
     * @return
     *     returns com.thesecretserver.service.AddSecretResult
     */
    @WebMethod(operationName = "AddSecret", action = "urn:thesecretserver.com/AddSecret")
    @WebResult(name = "AddSecretResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "AddSecret", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AddSecret")
    @ResponseWrapper(localName = "AddSecretResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AddSecretResponse")
    public AddSecretResult addSecret(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretTypeId", targetNamespace = "urn:thesecretserver.com")
        int secretTypeId,
        @WebParam(name = "secretName", targetNamespace = "urn:thesecretserver.com")
        String secretName,
        @WebParam(name = "secretFieldIds", targetNamespace = "urn:thesecretserver.com")
        ArrayOfInt secretFieldIds,
        @WebParam(name = "secretItemValues", targetNamespace = "urn:thesecretserver.com")
        ArrayOfString secretItemValues,
        @WebParam(name = "folderId", targetNamespace = "urn:thesecretserver.com")
        int folderId);

    /**
     * 
     * @param token
     * @param secretTypeId
     * @return
     *     returns com.thesecretserver.service.GetSecretTemplateFieldsResult
     */
    @WebMethod(operationName = "GetSecretTemplateFields", action = "urn:thesecretserver.com/GetSecretTemplateFields")
    @WebResult(name = "GetSecretTemplateFieldsResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetSecretTemplateFields", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretTemplateFields")
    @ResponseWrapper(localName = "GetSecretTemplateFieldsResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretTemplateFieldsResponse")
    public GetSecretTemplateFieldsResult getSecretTemplateFields(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretTypeId", targetNamespace = "urn:thesecretserver.com")
        int secretTypeId);

    /**
     * 
     * @param token
     * @param secret
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "UpdateSecret", action = "urn:thesecretserver.com/UpdateSecret")
    @WebResult(name = "UpdateSecretResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "UpdateSecret", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UpdateSecret")
    @ResponseWrapper(localName = "UpdateSecretResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UpdateSecretResponse")
    public WebServiceResult updateSecret(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secret", targetNamespace = "urn:thesecretserver.com")
        Secret secret);

    /**
     * 
     * @param token
     * @return
     *     returns com.thesecretserver.service.GetSecretTemplatesResult
     */
    @WebMethod(operationName = "GetSecretTemplates", action = "urn:thesecretserver.com/GetSecretTemplates")
    @WebResult(name = "GetSecretTemplatesResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetSecretTemplates", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretTemplates")
    @ResponseWrapper(localName = "GetSecretTemplatesResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretTemplatesResponse")
    public GetSecretTemplatesResult getSecretTemplates(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token);

    /**
     * 
     * @param token
     * @param secretFieldId
     * @return
     *     returns com.thesecretserver.service.GeneratePasswordResult
     */
    @WebMethod(operationName = "GeneratePassword", action = "urn:thesecretserver.com/GeneratePassword")
    @WebResult(name = "GeneratePasswordResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GeneratePassword", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GeneratePassword")
    @ResponseWrapper(localName = "GeneratePasswordResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GeneratePasswordResponse")
    public GeneratePasswordResult generatePassword(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretFieldId", targetNamespace = "urn:thesecretserver.com")
        int secretFieldId);

    /**
     * 
     * @param secretId
     * @param token
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "DeactivateSecret", action = "urn:thesecretserver.com/DeactivateSecret")
    @WebResult(name = "DeactivateSecretResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "DeactivateSecret", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.DeactivateSecret")
    @ResponseWrapper(localName = "DeactivateSecretResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.DeactivateSecretResponse")
    public WebServiceResult deactivateSecret(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId);

    /**
     * 
     * @return
     *     returns com.thesecretserver.service.VersionGetResult
     */
    @WebMethod(operationName = "VersionGet", action = "urn:thesecretserver.com/VersionGet")
    @WebResult(name = "VersionGetResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "VersionGet", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.VersionGet")
    @ResponseWrapper(localName = "VersionGetResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.VersionGetResponse")
    public VersionGetResult versionGet();

    /**
     * 
     * @param token
     * @param folderId
     * @return
     *     returns com.thesecretserver.service.GetFolderResult
     */
    @WebMethod(operationName = "FolderGet", action = "urn:thesecretserver.com/FolderGet")
    @WebResult(name = "FolderGetResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "FolderGet", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderGet")
    @ResponseWrapper(localName = "FolderGetResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderGetResponse")
    public GetFolderResult folderGet(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "folderId", targetNamespace = "urn:thesecretserver.com")
        int folderId);

    /**
     * 
     * @param modifiedFolder
     * @param token
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "FolderUpdate", action = "urn:thesecretserver.com/FolderUpdate")
    @WebResult(name = "FolderUpdateResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "FolderUpdate", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderUpdate")
    @ResponseWrapper(localName = "FolderUpdateResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderUpdateResponse")
    public WebServiceResult folderUpdate(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "modifiedFolder", targetNamespace = "urn:thesecretserver.com")
        Folder modifiedFolder);

    /**
     * 
     * @param token
     * @param parentFolderId
     * @return
     *     returns com.thesecretserver.service.GetFoldersResult
     */
    @WebMethod(operationName = "FolderGetAllChildren", action = "urn:thesecretserver.com/FolderGetAllChildren")
    @WebResult(name = "FolderGetAllChildrenResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "FolderGetAllChildren", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderGetAllChildren")
    @ResponseWrapper(localName = "FolderGetAllChildrenResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderGetAllChildrenResponse")
    public GetFoldersResult folderGetAllChildren(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "parentFolderId", targetNamespace = "urn:thesecretserver.com")
        int parentFolderId);

    /**
     * 
     * @param folderTypeId
     * @param token
     * @param parentFolderId
     * @param folderName
     * @return
     *     returns com.thesecretserver.service.CreateFolderResult
     */
    @WebMethod(operationName = "FolderCreate", action = "urn:thesecretserver.com/FolderCreate")
    @WebResult(name = "FolderCreateResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "FolderCreate", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderCreate")
    @ResponseWrapper(localName = "FolderCreateResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.FolderCreateResponse")
    public CreateFolderResult folderCreate(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "folderName", targetNamespace = "urn:thesecretserver.com")
        String folderName,
        @WebParam(name = "parentFolderId", targetNamespace = "urn:thesecretserver.com")
        int parentFolderId,
        @WebParam(name = "folderTypeId", targetNamespace = "urn:thesecretserver.com")
        int folderTypeId);

    /**
     * 
     * @param token
     * @param folderName
     * @return
     *     returns com.thesecretserver.service.SearchFolderResult
     */
    @WebMethod(operationName = "SearchFolders", action = "urn:thesecretserver.com/SearchFolders")
    @WebResult(name = "SearchFoldersResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "SearchFolders", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchFolders")
    @ResponseWrapper(localName = "SearchFoldersResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SearchFoldersResponse")
    public SearchFolderResult searchFolders(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "folderName", targetNamespace = "urn:thesecretserver.com")
        String folderName);

    /**
     * 
     * @param secretId
     * @param token
     * @return
     *     returns com.thesecretserver.service.FileDownloadResult
     */
    @WebMethod(operationName = "DownloadFileAttachment", action = "urn:thesecretserver.com/DownloadFileAttachment")
    @WebResult(name = "DownloadFileAttachmentResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "DownloadFileAttachment", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.DownloadFileAttachment")
    @ResponseWrapper(localName = "DownloadFileAttachmentResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.DownloadFileAttachmentResponse")
    public FileDownloadResult downloadFileAttachment(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId);

    /**
     * 
     * @param secretId
     * @param token
     * @param secretItemId
     * @return
     *     returns com.thesecretserver.service.FileDownloadResult
     */
    @WebMethod(operationName = "DownloadFileAttachmentByItemId", action = "urn:thesecretserver.com/DownloadFileAttachmentByItemId")
    @WebResult(name = "DownloadFileAttachmentByItemIdResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "DownloadFileAttachmentByItemId", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.DownloadFileAttachmentByItemId")
    @ResponseWrapper(localName = "DownloadFileAttachmentByItemIdResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.DownloadFileAttachmentByItemIdResponse")
    public FileDownloadResult downloadFileAttachmentByItemId(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId,
        @WebParam(name = "secretItemId", targetNamespace = "urn:thesecretserver.com")
        int secretItemId);

    /**
     * 
     * @param secretId
     * @param token
     * @param fileName
     * @param fileData
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "UploadFileAttachment", action = "urn:thesecretserver.com/UploadFileAttachment")
    @WebResult(name = "UploadFileAttachmentResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "UploadFileAttachment", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UploadFileAttachment")
    @ResponseWrapper(localName = "UploadFileAttachmentResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UploadFileAttachmentResponse")
    public WebServiceResult uploadFileAttachment(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId,
        @WebParam(name = "fileData", targetNamespace = "urn:thesecretserver.com")
        byte[] fileData,
        @WebParam(name = "fileName", targetNamespace = "urn:thesecretserver.com")
        String fileName);

    /**
     * 
     * @param secretId
     * @param token
     * @param fileName
     * @param secretItemId
     * @param fileData
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "UploadFileAttachmentByItemId", action = "urn:thesecretserver.com/UploadFileAttachmentByItemId")
    @WebResult(name = "UploadFileAttachmentByItemIdResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "UploadFileAttachmentByItemId", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UploadFileAttachmentByItemId")
    @ResponseWrapper(localName = "UploadFileAttachmentByItemIdResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.UploadFileAttachmentByItemIdResponse")
    public WebServiceResult uploadFileAttachmentByItemId(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId,
        @WebParam(name = "secretItemId", targetNamespace = "urn:thesecretserver.com")
        int secretItemId,
        @WebParam(name = "fileData", targetNamespace = "urn:thesecretserver.com")
        byte[] fileData,
        @WebParam(name = "fileName", targetNamespace = "urn:thesecretserver.com")
        String fileName);

    /**
     * 
     * @param secretId
     * @param token
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "ExpireSecret", action = "urn:thesecretserver.com/ExpireSecret")
    @WebResult(name = "ExpireSecretResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "ExpireSecret", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.ExpireSecret")
    @ResponseWrapper(localName = "ExpireSecretResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.ExpireSecretResponse")
    public WebServiceResult expireSecret(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId);

    /**
     * 
     * @param setPasswordChangeOnCheckIn
     * @param setCheckOut
     * @param secretId
     * @param checkOutInterval
     * @param token
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "SetCheckOutEnabled", action = "urn:thesecretserver.com/SetCheckOutEnabled")
    @WebResult(name = "SetCheckOutEnabledResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "SetCheckOutEnabled", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SetCheckOutEnabled")
    @ResponseWrapper(localName = "SetCheckOutEnabledResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.SetCheckOutEnabledResponse")
    public WebServiceResult setCheckOutEnabled(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId,
        @WebParam(name = "setCheckOut", targetNamespace = "urn:thesecretserver.com")
        boolean setCheckOut,
        @WebParam(name = "setPasswordChangeOnCheckIn", targetNamespace = "urn:thesecretserver.com")
        boolean setPasswordChangeOnCheckIn,
        @WebParam(name = "checkOutInterval", targetNamespace = "urn:thesecretserver.com")
        Integer checkOutInterval);

    /**
     * 
     * @param token
     * @param xml
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "ImportXML", action = "urn:thesecretserver.com/ImportXML")
    @WebResult(name = "ImportXMLResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "ImportXML", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.ImportXML")
    @ResponseWrapper(localName = "ImportXMLResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.ImportXMLResponse")
    public WebServiceResult importXML(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "xml", targetNamespace = "urn:thesecretserver.com")
        String xml);

    /**
     * 
     * @param secretId
     * @param token
     * @return
     *     returns com.thesecretserver.service.GetSecretAuditResult
     */
    @WebMethod(operationName = "GetSecretAudit", action = "urn:thesecretserver.com/GetSecretAudit")
    @WebResult(name = "GetSecretAuditResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetSecretAudit", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretAudit")
    @ResponseWrapper(localName = "GetSecretAuditResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetSecretAuditResponse")
    public GetSecretAuditResult getSecretAudit(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId);

    /**
     * 
     * @param token
     * @return
     *     returns com.thesecretserver.service.GetAgentsResult
     */
    @WebMethod(operationName = "GetAgents", action = "urn:thesecretserver.com/GetAgents")
    @WebResult(name = "GetAgentsResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "GetAgents", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetAgents")
    @ResponseWrapper(localName = "GetAgentsResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.GetAgentsResponse")
    public GetAgentsResult getAgents(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token);

    /**
     * 
     * @param secretId
     * @param token
     * @param agentId
     * @return
     *     returns com.thesecretserver.service.WebServiceResult
     */
    @WebMethod(operationName = "AssignAgent", action = "urn:thesecretserver.com/AssignAgent")
    @WebResult(name = "AssignAgentResult", targetNamespace = "urn:thesecretserver.com")
    @RequestWrapper(localName = "AssignAgent", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AssignAgent")
    @ResponseWrapper(localName = "AssignAgentResponse", targetNamespace = "urn:thesecretserver.com", className = "com.thesecretserver.service.AssignAgentResponse")
    public WebServiceResult assignAgent(
        @WebParam(name = "token", targetNamespace = "urn:thesecretserver.com")
        String token,
        @WebParam(name = "secretId", targetNamespace = "urn:thesecretserver.com")
        int secretId,
        @WebParam(name = "agentId", targetNamespace = "urn:thesecretserver.com")
        int agentId);

}
