#!/bin/bash

# /etc/init.d/w3act
#
# This SysV init script manages w3act services on RHEL
#
# 1. If needed change Linux run level to e.g. 3 use command 
#     init 3 
#
# 2. Copy this script from /opt/w3act/sysv/ folder to the /etc/init.d/ folder using command 
#     cp /opt/sysv/w3act /etc/init.d/ 
#
# 3. Add rights using command
#     chmod 755 /etc/init.d/w3act
#
# 4. Create symlink to the /etc/init.d/w3act script in required /etc/rc5.d level folder e.g. for the level 3 use commands
#     cd /etc/rc3.d
#     ln -s /etc/init.d/w3act S99w3act
#
# 5. To start the W3ACT application use e.g.
#     service w3act start
#
#    For application start we provide two parameters:
#        a. Database name -DapplyEvolutions.<databasename>=true e.g. w3act
#        b. Location for the file that contains the process id of the started application e.g. -Dpidfile.path=/var/run/play.pid
# 
# 6. To stop the W3ACT application use e.g.
#     service w3act stop
#
# chkconfig: 35 85 15
# description: W3ACT SysV init script
#
# Source function library.
. /etc/init.d/functions

PROJECT_ROOT=/opt/w3act-1.0
PLAY_DIR=/etc/default/play-2.2.0

case "$1" in
start)
	echo -n "Starting w3act services: "
	$PROJECT_ROOT/bin/w3act -DapplyEvolutions.default -Dpidfile.path=/var/run/play.pid
	touch /var/lock/subsys/w3act
;;
stop)
	echo -n "Shutting down w3act services: "
	kill $(cat /var/run/play.pid)
	rm -f /var/lock/subsys/w3act
;;
status)
	$PLAY_DIR/play status
;;
restart)
	kill $(cat /var/run/play.pid)
	rm -f /var/lock/subsys/w3act
	$PROJECT_ROOT/bin/w3act -DapplyEvolutions.default -Dpidfile.path=/var/run/play.pid
	touch /var/lock/subsys/w3act
;;
probe)
	$PLAY_DIR/play check
;;
*)
	echo "Usage: w3act {start|stop|status|restart[|probe]"
	exit 1
;;
esac
